#ifndef KERFUR_APP_EVENT_H_
#define KERFUR_APP_EVENT_H_

#include <stdint.h>

enum app_event_type {
	APP_EVENT_TICK_100MS = 0,
	APP_EVENT_TICK_1S,
	APP_EVENT_TICK_10S,
	APP_EVENT_TICK_60S,

	APP_EVENT_USER_TAP,
	APP_EVENT_USER_PET_SOFT,
	APP_EVENT_USER_PET_LONG,
	APP_EVENT_USER_HOLD,

	APP_EVENT_MOTION_WAKE,
	APP_EVENT_WALKING_START,
	APP_EVENT_WALKING_STOP,
	APP_EVENT_STEP_BATCH,
	APP_EVENT_SHAKE_LIGHT,
	APP_EVENT_SHAKE_PLAY,
	APP_EVENT_SHAKE_ROUGH,
	APP_EVENT_FLIP_FACE_DOWN,
	APP_EVENT_IMPACT,

	APP_EVENT_PHONE_CONNECTED,
	APP_EVENT_PHONE_DISCONNECTED,
	APP_EVENT_PHONE_NOTIFICATION_SINGLE,
	APP_EVENT_PHONE_NOTIFICATION_BURST,
	APP_EVENT_APP_SESSION_START,
	APP_EVENT_APP_SESSION_END,
	APP_EVENT_TIME_SYNC,

	APP_EVENT_CHARGER_CONNECTED,
	APP_EVENT_CHARGER_DISCONNECTED,
	APP_EVENT_BATTERY_LOW,
	APP_EVENT_BATTERY_CRITICAL,

	APP_EVENT_SELF_WAKE_TIMER,
	APP_EVENT_IDLE_TIMEOUT,
	APP_EVENT_WAKE,
	APP_EVENT_SLEEP_REQUEST,
	APP_EVENT_DISPLAY_FOREGROUND_TIMEOUT,
	APP_EVENT_DISPLAY_AMBIENT_TIMEOUT,

	APP_EVENT_COUNT
};

struct app_event {
	enum app_event_type type;
	int64_t timestamp_ms;
	int32_t param;
};

const char *app_event_type_str(enum app_event_type type);

/* Backward compatibility aliases for existing mock/debug plumbing. */
#define APP_EVENT_USER_BUTTON_PRESS APP_EVENT_USER_TAP
#define APP_EVENT_MOCK_PET APP_EVENT_USER_PET_SOFT
#define APP_EVENT_MOCK_SHAKE APP_EVENT_SHAKE_LIGHT
#define APP_EVENT_MOCK_NOTIFICATION APP_EVENT_PHONE_NOTIFICATION_BURST
#define APP_EVENT_PHONE_NOTIFICATION APP_EVENT_PHONE_NOTIFICATION_SINGLE
#define APP_EVENT_BLE_CONNECTED APP_EVENT_PHONE_CONNECTED
#define APP_EVENT_BLE_DISCONNECTED APP_EVENT_PHONE_DISCONNECTED

#endif /* KERFUR_APP_EVENT_H_ */
